include(":core:commons-general")
include(":core:trading-api")
include(":core:trading-transaq-impl")
include(":core:history-service")
include(":core:simulator")
include(":frontend:desktop")
include(":functional-tests")
include(":samples")